<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <BaseOutputPath>..\bin</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.4.0-ci1501" />
    <PackageReference Include="MaterialDesignThemes" Version="5.4.0-ci1501" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EIF-Simulator.Controls\EIF_Simulator.Controls.csproj" />
    <ProjectReference Include="..\EIF_Simulator.McProtocol\EIF_Simulator.McProtocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Simulator.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
